[package]
name = "relus_cli"
version = "0.1.1"
edition.workspace = true
authors = [""]


[package.metadata.packager]
# 1. 全局配置
formats = ["nsis"]
before-packaging-command = "cargo build --release"
# # 如果有资源文件，也放在这里
# resources = ["configs/**/*"]

[lib]
path = "src/lib.rs"

[dependencies]
relus_common = { workspace = true }
relus_connector_rdbms = { workspace = true }
clap = { workspace = true }

[lints]
workspace = true
